FROM maven:3.8.7-eclipse-temurin-8-alpine as build
WORKDIR /mavenwebapp
RUN mvn clean package

FROM tomcat:9.0-jre8-alpine
COPY --from=build /mavenwebapp/target/maven-web-application.war /usr/local/tomcat/webapps/maven-web-application.war